all: help

help:
	@echo ""
	@echo "-- Help Menu"
	@echo ""
	@echo "   1. make build          - build admm_slam image"
	# @echo "   1. make pull             - pull all images"
	# @echo "   1. make clean            - remove all images"
	@echo ""

build:
	@docker build --tag=admm_slam admm_slam/.

# pull:
# 	@docker pull admm_slam
#
# clean:
# 	@docker rmi -f admm_slam
